KissHiFi/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KissHiFi.Code;
using KissHiFi.DAL;
using KissHiFi.Models;

namespace KissHiFi.Controllers
{
    public class AdminController : Controller
    {
        UnitOfWork unitOfWork = new UnitOfWork();
        RouteName script = new RouteName();

        //
        // GET: /Admin/

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Hirek()
        {
            return RedirectToAction("AdminIndex", "Hirek");
        }

        [Authorize]
        public ActionResult Bemutatkozas()
        {
            return RedirectToAction("Edit", "Bemutatkozas");
        }

        [Authorize]
        public ActionResult Szolgaltatas()
        {
            return RedirectToAction("Edit", "Szolgaltatas");
        }

        [Authorize]
        public ActionResult Termek()
        {
            return
                View(
                    unitOfWork.TermekAdatlapRepository.Get(null, q => q.OrderBy(k => k.TermekKategoria.Nev))
                              .OrderBy(m => m.TermekMarka.Nev)
                              .ThenBy(a => a.Tipus));
        }

        [Authorize]
        public ActionResult TermekUj()
        {
            ViewBag.Kategoria = KategoriaList();
            ViewBag.Marka = MarkaList();

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TermekUj(TermekAdatlap model, HttpPostedFileBase file)
        {
            try
            {
                model.RouteNev = script.RouteNev(model.Tipus);

                if (file != null && file.ContentLength > 0 && file.ContentType == "image/jpg" || file.ContentType == "image/jpeg")
                {
                    string fileName = script.FileNev(Path.GetFileName(file.FileName));
                    var path = Path.Combine(Server.MapPath("~/Content/Termekek"), fileName);
                    file.SaveAs(path);

                    model.Kep = fileName;

                    unitOfWork.TermekAdatlapRepository.Insert(model);
                    unitOfWork.Save();

                    return RedirectToAction("Termek");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError(string.Empty,"Nem sikerült a mentés");
            }
            return View(model);
        }

        [Authorize]
        public ActionResult TermekEdit(string id)
        {
            ViewBag.Kategoria = KategoriaList();
            ViewBag.Marka = MarkaList();

            return View(unitOfWork.TermekAdatlapRepository.Get(x => x.RouteNev == id).FirstOrDefault());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TermekEdit(TermekAdatlap model)
        {
            try
            {
                model.TermekKategoriaId = Convert.ToInt32(model.TermekKategoriaId);
                model.TermekMarkaId = Convert.ToInt32(model.TermekMarkaId);

                if (ModelState.IsValid)
                {
                    unitOfWork.TermekAdatlapRepository.Update(model);
                    unitOfWork.Save();

                    return RedirectToAction("Termek");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError(string.Empty, "Nem sikerült a mentés");
            }
            return View(model);
        }

        [Authorize]
        public ActionResult Elerhetoseg()
        {
            return RedirectToAction("Edit", "Elerhetoseg");
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateKategoria(TermekKategoria model, HttpPostedFileBase file, bool uj)
        {
            try
            {
                if (file != null && file.ContentLength > 0 && (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg"))
                {
                    string fileName = script.FileNev(Path.GetFileName(file.FileName));
                    var path = Path.Combine(Server.MapPath("~/Content/Termekek/Kategoria"), fileName);
                    file.SaveAs(path);

                    model.Kep = fileName;

                    model.RouteNev = script.RouteNev(model.Nev);
                    unitOfWork.TermekKategoriaRepository.Insert(model);
                    unitOfWork.Save();

                    if (uj)
                    {
                        return RedirectToAction("TermekUj");
                    }
                    {
                        return RedirectToAction("TermekEdit");
                    }
                }
                ModelState.AddModelError(string.Empty,"Nem sikrült a mentés.\nCsak JPG és JPEG fájokat fogad el az oldal.");
                if (uj)
                {
                    return RedirectToAction("TermekUj");
                }
                {
                    return RedirectToAction("TermekEdit");
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Nem sikrült a mentés.");
                if (uj)
                {
                    return RedirectToAction("TermekUj");
                }
                {
                    return RedirectToAction("TermekEdit");
                }
            }
        }

        [Authorize]
        public ActionResult CreateMarka(TermekMarka model, HttpPostedFileBase file, bool uj)
        {
            try
            {
                if (file != null && file.ContentLength > 0 && (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg"))
                {
                    string fileName = script.FileNev(Path.GetFileName(file.FileName));
                    var path = Path.Combine(Server.MapPath("~/Content/Termekek/Marka"), fileName);
                    file.SaveAs(path);

                    model.Kep = fileName;

                    model.RouteNev = script.RouteNev(model.Nev);
                    unitOfWork.TermekMarkaRepository.Insert(model);
                    unitOfWork.Save();

                    if (uj)
                    {
                        return RedirectToAction("TermekUj");
                    }
                    {
                        return RedirectToAction("TermekEdit");
                    }
                }
                ModelState.AddModelError(string.Empty, "Nem sikrült a mentés.\nCsak JPG és JPEG fájokat fogad el az oldal.");
                if (uj)
                {
                    return RedirectToAction("TermekUj");
                }
                {
                    return RedirectToAction("TermekEdit");
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Nem sikrült a mentés.");
                if (uj)
                {
                    return RedirectToAction("TermekUj");
                }
                {
                    return RedirectToAction("TermekEdit");
                }
            }
        }

        [Authorize]
        public ActionResult Kepek()
        {
            return View();
        }

        [Authorize]
        public ActionResult SaveUploadedFile()
        {
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                if (file.ContentLength > 0 && (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg"))
                {
                    var fName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Kepek"), fName);
                    file.SaveAs(path);
                }
            }
            return RedirectToAction("Kepek");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Kepek(IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file.ContentLength > 0 && (file.ContentType == "image/jpg" || file.ContentType == "image/jpeg"))
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Kepek"), fileName);
                    file.SaveAs(path);
                }
            }
            return View();
        }

        [Authorize]
        private IOrderedEnumerable<SelectListItem> KategoriaList()
        {
            var kat = (from k in unitOfWork.TermekKategoriaRepository.Get()
                       select k).AsEnumerable().Select(x => new SelectListItem
                           {
                               Text = x.Nev,
                               Value = Convert.ToString(x.Id)
                           }).OrderBy(x => x.Text);
            return kat;
        }

        [Authorize]
        private IOrderedEnumerable<SelectListItem> MarkaList()
        {
            var marka = (from m in unitOfWork.TermekMarkaRepository.Get()
                         select m).AsEnumerable().Select(x => new SelectListItem
                             {
                                 Text = x.Nev,
                                 Value = Convert.ToString(x.Id)
                             }).OrderBy(x => x.Text);
            return marka;
        }
    }
}

KissHiFi/Controllers/TermekekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AttributeRouting.Web.Mvc;
using KissHiFi.DAL;
using KissHiFi.ViewModel;

namespace KissHiFi.Controllers
{
    public class TermekekController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Termekek/

        public ActionResult Index()
        {
            return View(unitOfWork.TermekAdatlapRepository.Get().OrderBy(x => x.TermekKategoria.Nev));
        }

        [GET("Termekek/{kategoria}/{marka}/{termek}")]
        public ActionResult Adatlap(string kategoria, string marka, string termek)
        {
            return View(unitOfWork.TermekAdatlapRepository.Get(x => x.RouteNev == termek).FirstOrDefault());
        }

        [GET("Termekek/{kategoria}/{marka}")]
        public ActionResult IndexByMarka(string kategoria, string marka)
        {
            ViewBag.Kategoria = kategoria;
            ViewBag.Marka = marka;

            ViewBag.aktKategoria =
                unitOfWork.TermekKategoriaRepository.Get(x => x.RouteNev == kategoria)
                          .Select(x => x.Nev)
                          .FirstOrDefault();

            ViewBag.aktMarka =
                unitOfWork.TermekMarkaRepository.Get(x => x.RouteNev == marka).Select(x => x.Nev).FirstOrDefault();

            return
                View(
                    unitOfWork.TermekAdatlapRepository.Get(x => x.TermekKategoria.RouteNev == kategoria)
                              .Where(x => x.TermekMarka.RouteNev == marka));
        }

        [GET("Termekek/{kategoria}")]
        public ActionResult IndexByCategory(string kategoria)
        {
            ViewBag.Kategoria = kategoria;

            ViewBag.aktKategoria =
                unitOfWork.TermekKategoriaRepository.Get(x => x.RouteNev == kategoria)
                          .Select(x => x.Nev)
                          .FirstOrDefault();

            var marka =
                unitOfWork.TermekAdatlapRepository.Get(x => x.TermekKategoria.RouteNev == kategoria);

            return View(marka);
        }
    }
}

KissHiFi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Hi-Fi Kiss</title>
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</head>
    <body>
        <nav>
            <img src="~/Content/themes/base/images/banner.png" />
            <ul>
                <li>@Html.ActionLink("Hírek","Index","Hirek")</li>
                <li>@Html.ActionLink("Bemutatkozás","Index","Bemutatkozas")</li>
                <li>@Html.ActionLink("Szolgáltatások","Index","Szolgaltatas")</li>
                <li>@Html.ActionLink("Termékek","Index","Termekek")</li>
                <li>@Html.ActionLink("Zene", "Index", "Zene")</li>
                <li>@Html.ActionLink("Képek","Index","Kepek")</li>
                <li>@Html.ActionLink("Elérhetőség","Index","Elerhetoseg")</li>
            </ul>
        </nav>
        <section>
            @RenderBody()
        </section>
        <footer>
            A weblapot készítette: Barasits Péter - &copy; 2013 - @DateTime.Now.Year
        </footer>
    </body>
</html>

KissHiFi/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Hi-Fi Kiss</title>
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</head>
    <body>
        <nav>
            <img src="~/Content/themes/base/images/banner.png" />
            <ul>
                <li>@Html.ActionLink("Hírek","Index","Hirek")</li>
                <li>@Html.ActionLink("Bemutatkozás","Index","Bemutatkozas")</li>
                <li>@Html.ActionLink("Szolgáltatások","Index","Szolgaltatas")</li>
                <li>@Html.ActionLink("Termékek","Index","Termekek")</li>
                <li>@Html.ActionLink("Képek","Index","Kepek")</li>
                <li>@Html.ActionLink("Elérhetőség","Index","Elerhetoseg")</li>
            </ul>
        </nav>
        <section>
                    <aside>
            Admin menü:
            <ul>
                <li>@Html.ActionLink("Hírek","Hirek","Admin")</li>
                <li>@Html.ActionLink("Bemutatkozás","Bemutatkozas","Admin")</li>
                <li>@Html.ActionLink("Szolgáltatások","Szolgaltatas","Admin")</li>
                <li>@Html.ActionLink("Termékek","Termek","Admin")</li>
                <li>@Html.ActionLink("Képek","Kepek","Admin")</li>
                <li>@Html.ActionLink("Elérhetőség","Elerhetoseg","Admin")</li>
                <li>@Html.ActionLink("Regisztració","Registration","Account")</li>
                <li>@Html.ActionLink("Kijelentkezés","LogOut","Account")</li>
            </ul>
        </aside>
            @RenderBody()
        </section>
        <footer>
            A weblapot készítette: Barasits Péter - &copy; 2013 - @DateTime.Now.Year
        </footer>
    </body>
</html>